### PR TITLE
Allow CustomEvent to be created

### PR DESCRIPTION
**Pull request by SheepFromHeaven**
Currently basicHTML is throwing an error when using HyperHTML element as it uses hyperHTML which uses @ungap/custom-event to create custom events.

This invokes `document.createEvent('CustomEvent')` which is not handled by basicHTML.

I added the changes needed to make this possible.

### CODE REVIEW

**Comment by WebReflection** [comment]
Good catch, and good PR, however I'd like to keep the code coverage 100%.

Do you mind adding a test for that case too?

**Comment by SheepFromHeaven** [comment]
Yep, will do! 👍

**Comment by SheepFromHeaven** [comment]
Good thing you did this. Found an actual error 🥇

**Comment by WebReflection** [comment]
> Good thing you did this. Found an actual error

that's why I want to keep it 100% ;-) I'm used to little gotchas every single time I forget to add a test so thanks for adding it.

**Comment by WebReflection** [comment]
up and running @ `v0.21`

**Comment by SheepFromHeaven** [comment]
@WebReflection yay! will update

**Pull request merged**
